plugins {
    id("idea")
    id("eclipse")
    id("maven-publish")
    id("net.kyori.blossom") version "2.2.0"
    id("dev.ithundxr.silk") version "1.0.1"
    id("net.neoforged.moddev") version "2.0.144"
    id("me.modmuss50.mod-publish-plugin") version "1.1.0"
}

boolean dev = System.getenv("RELEASE") == null || System.getenv("RELEASE") == "false"
String buildNumber = System.getenv("BUILD_NUMBER")
String gitHash = calculateGitHash() + (hasUnstaged() ? "-modified" : "")

group = "com.simibubi.create"
version = mod_version + (dev && buildNumber != null ? "-${buildNumber}" : "")

java {
    toolchain.languageVersion = JavaLanguageVersion.of(25)
    withSourcesJar()
}

println("Java: ${System.getProperty("java.version")}, JVM: ${System.getProperty("java.vm.version")} (${System.getProperty("java.vendor")}), Arch: ${System.getProperty("os.arch")}")

idea {
    module {
        downloadJavadoc = true
        downloadSources = true
    }
}

neoForge {
    version = neo_version

    accessTransformers {
        publish(file("src/main/resources/META-INF/accesstransformer.cfg"))
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }

    runs {
        configureEach {
            systemProperty("forge.logging.markers", "REGISTRIES")
            jvmArgument("-XX:+IgnoreUnrecognizedVMOptions")
            jvmArgument("-XX:+AllowEnhancedClassRedefinition")
            systemProperty("mixin.debug.verbose", "true")
            systemProperty("mixin.debug.export", "true")
            systemProperty("neoforge.enabledGameTestNamespaces", mod_id as String)
            loggingConfigFile = project.file("log4j.xml")
        }

        client {
            client()
        }

        server {
            server()
            gameDirectory = project.file("run/server")
            programArgument("--nogui")
        }

        data {
            data()
            programArguments.addAll(
                "--mod", mod_id as String,
                "--all",
                "--output", file("src/generated/resources/").getAbsolutePath(),
                "--existing", file("src/main/resources/").getAbsolutePath()
            )
        }

        gameTestServer {
            type = "gameTestServer"
        }
    }
}

repositories {
    maven { url = "https://maven.createmod.net" }
    maven { url = "https://maven.ithundxr.dev/snapshots" }
    maven { url = "https://maven.blamejared.com" }
    maven { url = "https://maven.theillusivec4.top/" }
    maven { url = "https://maven.squiddev.cc" }
    maven { url = "https://www.cursemaven.com" }
    maven { url = "https://api.modrinth.com/maven" }
    maven { url = "https://maven.ftb.dev/releases" }
    maven { url = "https://maven.architectury.dev" }
    maven { url = "https://raw.githubusercontent.com/Fuzss/modresources/main/maven" }
    maven {
        url = "https://jm.gserv.me/repository/maven-public"
        content {
            includeGroup "info.journeymap"
            includeGroup "mysticdrew"
        }
    }
    maven { url = "https://chocolateminecraft.com/maven" }
}

configurations {
    localImplementation
    runtimeClasspath.extendsFrom(localImplementation)
    compileClasspath.extendsFrom(localImplementation)
    runtimeClasspath.extendsFrom(localRuntimeOnly)
}

dependencies {
    jarJar(api("com.tterrag.registrate:Registrate:$registrate_version"))

    compileOnlyApi("dev.engine-room.flywheel:flywheel-neoforge-api-$minecraft_version:$flywheel_version")
    jarJar(runtimeOnly("dev.engine-room.flywheel:flywheel-neoforge-$minecraft_version:$flywheel_version") {
        version {
            strictly "[${flywheel_version},2.0)"
            prefer flywheel_version
        }
    })

    jarJar(api("net.createmod.ponder:ponder-neoforge:$ponder_version+mc$minecraft_version") {
        version {
            strictly "[$ponder_version+mc$minecraft_version,)"
            prefer "$ponder_version+mc$minecraft_version"
        }
    })

    localRuntimeOnly("dev.engine-room.vanillin:vanillin-neoforge-$minecraft_version:$vanillin_version")

    localImplementation("mezz.jei:jei-$minecraft_version-neoforge:$jei_version")
    compileOnly("top.theillusivec4.curios:curios-neoforge:$curios_version+$minecraft_version:api")
    localRuntimeOnly("top.theillusivec4.curios:curios-neoforge:$curios_version+$minecraft_version")
    compileOnly("maven.modrinth:sodium:mc$minecraft_version-$sodium_version-neoforge")

    if (cc_tweaked_enable.toBoolean()) {
        compileOnly("cc.tweaked:cc-tweaked-$minecraft_version-core-api:$cc_tweaked_version")
        compileOnly("cc.tweaked:cc-tweaked-$minecraft_version-forge-api:$cc_tweaked_version")
        localRuntimeOnly("cc.tweaked:cc-tweaked-$minecraft_version-forge:$cc_tweaked_version")
    }

    compileOnly("maven.modrinth:farmers-delight:${farmers_delight_version}")
    if (farmers_delight_enable.toBoolean()) {
        localImplementation("maven.modrinth:farmers-delight:${farmers_delight_version}")
    }

    localRuntimeOnly("dev.architectury:architectury-neoforge:13d.0.8")
    localImplementation("dev.ftb.mods:ftb-chunks-neoforge:2101.1.1")
    localImplementation("dev.ftb.mods:ftb-teams-neoforge:2101.1.0")
    localImplementation("dev.ftb.mods:ftb-library-neoforge:2101.1.3")

    localImplementation("maven.modrinth:journeymap:1.21.1-6.0.0-beta.54+neoforge")
    localImplementation("info.journeymap:journeymap-api-neoforge:2.0.0-1.21.1-20260205.200232-15") {
        exclude(group: "curse.maven")
    }

    compileOnly("xaero.lib:xaerolib-neoforge-1.21:1.0.42")
    compileOnly("curse.maven:xaeros-world-map-317780:7401095")
}
